services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
     - mongo_data:/data/db 
    
  basketdb:
    container_name: basketdb
    restart: always
    ports:
     - "6379:6379"
   
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@1
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data/


  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eCommerce.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin



  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSetting__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://localhost:8002"
    depends_on: 
     - basketdb
    ports:
      - "8001:8080"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200" 
    depends_on:
      - discountdb
    ports:
      - "8002:8080" 
   


