services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
     - mongo_data:/data/db 
    
  basketdb:
    container_name: basketdb
    restart: always
    ports:
     - "6379:6379"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSetting__ConnectionString=basketdb:6379"
    depends_on: 
     - basketdb
    ports:
      - "8081:8080"

